#Default network configuration
#Layout for UNO-2484G

#LAN A: enp0s31f6
#LAN B: enp1s0
#LAN C: enp3s0
#LAN D: enp2s0

network:
  renderer: NetworkManager
  ethernets:
    enp2s0:
      dhcp4: true
      addresses:
      - 169.254.0.1/24

  version: 2
