# This is the network config written by 'subiquity'
network:
  renderer: NetworkManager
  ethernets:
    enp0s31f6:
      dhcp4: true
    enp1s0:
      dhcp4: true
    enp2s0:
      dhcp4: true
    enp3s0:
      dhcp4: true
  version: 2
